name: py_flask_trade
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - pydantic==1.9.0
    - Lin-CMS==0.4.10
    - pillow==9.3.0
    - flask-cors==3.0.10
    - gunicorn==20.1.0
    - gevent==21.8.0
    - flask-socketio==5.1.1
    - blinker==1.4
    - python-dotenv==0.19.2
    - gevent-websocket==0.10.1
    - flask-sqlacodegen==1.1.8
    - isort==5.10.1
    - watchdog==2.1.6
    - coverage==6.3.2
    - pytest==6.2.5
    - pre-commit==2.17.0
    - pytest-ordering==0.6
    - flake8==4.0.1
    - Werkzeug==2.1.2
    - aioredis==2.0.1
    - hiredis==2.2.2
    - flask_redis==0.4.0
    - redis==4.5.1
    - easytrader==0.23.0
    - flask_apscheduler==1.12.4
    - apscheduler==3.10.1
    - tzlocal==4.2
    - tzdata==2022.7
    - pymysql
    # - pypiwin32==223 